Drinkbox/Web/Components/CartSummaryViewComponent.cs
using Drinkbox.Infrastructure.Services.CartItems;
using Microsoft.AspNetCore.Mvc;

namespace Drinkbox.Web.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly ICartItemService _cartItemService;
        public CartSummaryViewComponent(ICartItemService cartItemService)
        {
            _cartItemService = cartItemService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            _cartItemService.LoadCart();
            var count = _cartItemService.CartItems.Count;
            return View(count);
        }
    }
}

Drinkbox/Web/Components/ImportViewComponent.cs
using Drinkbox.Infrastructure.Services.CartItems;
using Drinkbox.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Drinkbox.Web.Components
{
    public class ImportViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(new ImportExcelViewModel());
        }
    }
}

Drinkbox/Web/Views/Home/Index.cshtml
@using Drinkbox.Web.ViewModels
@model ProductsViewModel

@{
    ViewData["Title"] = "Каталог напитков";
}

<div class="product-page">
    <div>
        <h1 class="page-title">Газированные напитки</h1>
    </div>
    <div class="filters-container">
        <div class="filter-select">
            <label class="filter-label">Выберите бренд</label>
            <select class="brand-select" 
                    asp-items="Model.Brands">
                <option value="">Все бренды</option>
            </select>
        </div>
        <div class="price-filter">
            <label class="filter-label">Стоимость</label>
            <div class="f-inline">
                <label class="min-price">0 руб.</label>
                <label class="max-price">0 руб.</label>
            </div>
            <input type="range" min="0" max="200" value=0 step="5" />
        </div>
        <div class="button-container">
            @(await Component.InvokeAsync("Import"))
            @(await Component.InvokeAsync("CartSummary"))
        </div>
    </div>
    <section>
        <div class="product-grid">
            @await Html.PartialAsync("_ProductListPartial", Model)
        </div>
    </section>
    <script src="~/js/products.js"></script>
</div>

Drinkbox/Web/Views/Home/_ProductListPartial.cshtml
@using Drinkbox.Web.ViewModels
@model ProductsViewModel

@foreach (var prod in Model.Products)
{
    <div class="product-card">
        <div class="product-image-container">
            <img class="product-image" src="@prod.ImageUrl" />
        </div>
        <div class="product-info">
            <h3 class="product-name">@prod.ProductName</h3>
            <div class="product-price">@prod.Price руб.</div>
            @if (prod.IsActive)
            {
                <button type="button"
                    class="product-button @(Model.ProductsInCart.Contains(prod.ProductId) ? "selected" : "")"
                    data-product-id="@prod.ProductId"
                    data-selected="@Model.ProductsInCart.Contains(prod.ProductId).ToString().ToLower()">
                    @(Model.ProductsInCart.Contains(prod.ProductId) ? "Выбрано" : "Выбрать")
                </button>
            }
            else
            {
                <button data-product-id="@prod.ProductId" class="product-close-button">Закончился</button>
            }
        </div>
    </div>
}
@if (!Model.Products.Any())
{
    <div class="no-products">
        <p>Нет товаров по выбранному фильтру</p>
    </div>
}